name: CI

on: push

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        version: ['1.3', '1.4', '1.5']
        os: [ubuntu-latest]

    steps:
      - name: Checkout InvertibleNetworks.jl
        uses: actions/checkout@v2

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - name: Add SLIM registery for JOLI
        run: |
           julia --color=yes --check-bounds=yes -e 'using Pkg;Pkg.update();Pkg.Registry.add(RegistrySpec(url="https://github.com/slimgroup/SLIMregistryJL.git"))'


      - name: Build InvertibleNetworks.jl
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest

      - name: Run simple example
        if: runner.os == 'linux'
        run: julia --project examples/layers/layer_actnorm.jl
